lex(pronoun,sing,first,objective,masc,me).
lex(pronoun,sing,first,objective,fem,me).
lex(pronoun,sing,first,objective,neut,me).
lex(pronoun,sing,first,possesive-determiner,masc,my).
lex(pronoun,sing,first,possesive-determiner,fem,my).
lex(pronoun,sing,first,possesive-determiner,neut,my).
lex(pronoun,sing,first,possesive-nominal,masc,mine).
lex(pronoun,sing,first,possesive-nominal,fem,mine).
lex(pronoun,sing,first,possesive-nominal,neut,mine).
lex(pronoun,plur,first,subjective,masc,we).
lex(pronoun,plur,first,subjective,fem,we).
lex(pronoun,plur,first,subjective,neut,we).
lex(pronoun,plur,first,objective,masc,us).
lex(pronoun,plur,first,objective,fem,us).
lex(pronoun,plur,first,objective,neut,us).
lex(pronoun,plur,first,possesive-determiner,masc,our).
lex(pronoun,plur,first,possesive-determiner,fem,our).
lex(pronoun,plur,first,possesive-determiner,neut,our).
lex(pronoun,plur,first,possesive-nominal,masc,ours).
lex(pronoun,plur,first,possesive-nominal,fem,ours).
lex(pronoun,plur,first,possesive-nominal,neut,ours).
lex(pronoun,plur,second,subjective,masc,you).
lex(pronoun,plur,second,subjective,fem,you).
lex(pronoun,plur,second,subjective,neut,you).
lex(pronoun,sing,second,subjective,masc,you).
lex(pronoun,sing,second,subjective,fem,you).
lex(pronoun,sing,second,subjective,neut,you).
lex(pronoun,sing,third,subjective,masc,he).
lex(pronoun,sing,third,objective,masc,him).
lex(pronoun,sing,third,possesive-determiner,masc,his).
lex(pronoun,sing,third,possesive-nomimal,masc,his).
lex(pronoun,sing,third,subjective,fem,she).
lex(pronoun,sing,third,objective,fem,her).
lex(pronoun,sing,third,possesive-determiner,fem,her).
lex(pronoun,sing,third,possesive-nominal,fem,hers).
lex(pronoun,plur,third,subjective,neut,it).
lex(pronoun,plur,third,objective,neut,it).
lex(pronoun,plur,third,possesive-determiner,neut,its).
lex(pronoun,plur,third,possesive-nomimal,neut,its).
lex(pronoun,plur,third,subjective,masc,they).
lex(pronoun,plur,third,subjective,fem,they).
lex(pronoun,plur,third,subjective,neut,they).
lex(pronoun,plur,third,objective,masc,them).
lex(pronoun,plur,third,objective,fem,them).
lex(pronoun,plur,third,objective,neut,them).
lex(pronoun,plur,third,possesive-determiner,masc,their).
lex(pronoun,plur,third,possesive-determiner,fem,their).
lex(pronoun,plur,third,possesive-determiner,neut,their).
lex(pronoun,plur,third,possesive-nominal,masc,theirs).
lex(pronoun,plur,third,possesive-nominal,fem,theirs).
lex(pronoun,plur,third,possesive-nominal,neut,theirs).
lex(pronoun,sing,first,reflexive,masc,myself).
lex(pronoun,sing,first,reflexive,fem,myself).
lex(pronoun,sing,first,reflexive,neut,myself).
lex(pronoun,plur,first,reflexive,masc,ourselves).
lex(pronoun,plur,first,reflexive,fem,ourselves).
lex(pronoun,plur,first,reflexive,neut,ourselves).
lex(pronoun,sing,second,reflexive,masc,yourself).
lex(pronoun,sing,second,reflexive,fem,yourself).
lex(pronoun,sing,second,reflexive,neut,yourself).
lex(pronoun,plur,second,reflexive,masc,yourselves).
lex(pronoun,plur,second,reflexive,fem,yourselves).
lex(pronoun,plur,second,reflexive,neut,yourselves).
lex(pronoun,sing,third,reflexive,masc,himself).
lex(pronoun,sing,third,reflexive,fem,herself).
lex(pronoun,sing,third,reflexive,neut,itself).
lex(pronoun,plur,third,reflexive,masc,themselves).
lex(pronoun,plur,third,reflexive,fem,themselves).
lex(pronoun,plur,third,reflexive,neut,themselves).
lex(pronoun,sing,third,subjective,neut,_).
lex(pronoun,sing,third,objective,neut,_).
lex(noun,countable,sing,neut,company).
lex(noun,countable,plur,neut,companies).
lex(noun,countable,sing,neut,department).
lex(noun,countable,plur,neut,departments).
lex(noun,countable,sing,neut,person).
lex(noun,countable,plur,neut,persons).
lex(noun,countable,sing,masc,man).
lex(noun,countable,plur,masc,men).
lex(noun,countable,sing,fem,woman).
lex(noun,countable,plur,fem,women).
lex(noun,countable,sing,neut,employee).
lex(noun,countable,plur,neut,employees).
lex(noun,countable,sing,neut,dog).
lex(noun,countable,plur,neut,dogs).
lex(noun,countable,sing,neut,salary).
lex(noun,countable,plur,neut,salaries).
lex(noun,countable,sing,neut,position).
lex(noun,countable,plur,neut,positions).
lex(noun,countable,sing,neut,budget).
lex(noun,countable,plur,neut,budgets).
lex(noun,countable,sing,neut,computer).
lex(noun,countable,plur,neut,computers).
lex(noun,countable,plur,neut,service).
lex(noun,countable,plur,neut,services).
lex(noun,countable,sing,neut,boss).
lex(noun,countable,plur,neut,bosses).
lex(noun,countable,plur,neut,people).
lex(noun,countable,plur,neut,goods).
lex(noun,countable,sing,neut,flight).
lex(noun,countable,plur,neut,flights).
lex(noun,countable,sing,neut,fare).
lex(noun,countable,sing,neut,fares).
lex(noun,countable,sing,neut,dollar).
lex(noun,countable,plur,neut,dollars).
lex(noun,countable,sing,neut,reservation).
lex(noun,countable,plur,neut,reservations).
lex(noun,countable,sing,neut,breeze).
lex(noun,countable,plur,neut,breeze).
lex(noun,mass,sing,neut,music).
lex(noun,mass,plur,neut,music).
lex(noun,mass,sing,neut,math).
lex(noun,mass,plur,neut,math).
lex(noun,mass,sing,neut,water).
lex(noun,mass,plur,neut,water).
lex(pronoun,sing,first,subjective,_).
lex(verb,plur,first,present,investigate).
lex(verb,sing,first,present,investigate).
lex(verb,plur,third,present,investigate).
lex(verb,sing,third,present,investigate).
lex(verb,plur,first,present,investigate).
lex(verb,sing,first,present,investigate).
lex(verb,plur,second,present,investigate).
lex(verb,sing,second,present,investigate).
lex(verb,plur,third,present,investigate).
lex(verb,sing,third,present,investigate).
lex(verb,singular,third,present,deserves).
lex(verb,plur,first,past,said).
lex(verb,sing,first,past,said).
lex(verb,plur,second,past,said).
lex(verb,sing,second,past,said).
lex(verb,plur,third,past,said).
lex(verb,sing,third,past,said).
lex(verb,plur,first,past-participle,conducted).
lex(verb,plur,second,past-participle,conducted).
lex(verb,plur,third,past-participle,conducted).
lex(verb,sing,first,past-participle,conducted).
lex(verb,sing,second,past-participle,conducted).
lex(verb,sing,third,past-participle,conducted).
lex(relative_pronoun,accusative,male,who).
lex(relative_pronoun,accusative,female,who).
lex(relative_pronoun,accusative,neut,that).
lex(relative_pronoun,nominative,male,who).
lex(relative_pronoun,nominative,female,who).
lex(relative_pronoun,nominative,neut,that).
lex(relative_pronoun,genitive,male,whose).
lex(relative_pronoun,genitive,female,whose).
lex(determiner,sing,a).
lex(determiner,plur,the).
lex(determiner,plur,which).
lex(determiner,sing,which).
lex(cardinal,sing,one).
lex(cardinal,plur,one).
lex(ordinal,plur,first).
lex(ordinal,sing,first).
lex(ordinal,plur,many).
lex(adjective,expensive).
lex(wh_determiner,which).
lex(quantifier,first-class).
lex(conjunction,and).
lex(preposition,from).
lex(gerund_verb,being).
lex(modal_verb,should).
