require 'brown_corpus.rb'
include Corpus

BROWN_CORPUS_DIR="/usr/share/nltk/data/corpora/brown"
OUTPUT_FILE="../../grammars/english/brown_corpus.pl"

HEADER = <<EOD
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The Brown corpus converted to Prolog facts.
% This file is generated by scripts/brown/brown_to_prolog.rb
% 
% Each unique word/tag combination is a fact: brown_pos_tag(Word,Tag).
% Each sentence is a fact brown_sentence(Number, [[Word1,Tag1],[Word2,Tag2], ...]).
% Number is the a unique number, according to a numbering scheme such that the Number 
% of the first sentence is 1 and so forth.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

EOD

File.open(OUTPUT_FILE,"w") do |file|
  file << HEADER
  file << BrownCorpus.new(BROWN_CORPUS_DIR).to_prolog
end
