tagword(fw-at+np,[fw-at+np]).
tagword(fw-jjr,[fw-jjr]).
tagword(wdt+ber+pp,[wdt+ber+pp]).
tagword(jjr+cs,[jjr+cs]).
tagword(fw-hv,[fw-hv]).
tagword(fw-pn,[fw-pn]).
tagword(fw-be,[fw-be]).
tagword(fw-pps,[fw-pps]).
tagword(fw-to+vb,[fw-to+vb]).
tagword(jj-s,[jj-s]).
tagword(fw-rb+cc,[fw-rb+cc]).
tagword(fw-wpo,[fw-wpo]).
tagword(fw-vbd,[fw-vbd]).
tagword(fw-cd,[fw-cd]).
tagword(fw-nps,[fw-nps]).
tagword(fw-wps,[fw-wps]).
tagword(fw-ppl+vbz,[fw-ppl+vbz]).
tagword(fw-ppo+in,[fw-ppo+in]).
tagword(fw-dts,[fw-dts]).
tagword(ppss+ber-n,[ppss+ber-n]).
tagword(nn+nn,[nn+nn]).
tagword(jj+jj,[jj+jj]).
tagword(ap+ap,[ap+ap]).
tagword(vb+jj,[vb+jj]).
tagword(vb+vb,[vb+vb]).
tagword(fw-in+at-t,[fw-in+at-t]).
tagword(fw-dt,[fw-dt]).
tagword(fw-ql,[fw-ql]).
tagword(fw-jjt,[fw-jjt]).
tagword(discard,[discard]).
tagword(acre,[acre]).
tagword(nil,[nil]).
tagword(fw-dt+bez,[fw-dt+bez]).
tagword(vb+in,[vb+in]).
tagword(md+ppss,[md+ppss]).
tagword(wdt+hvz,[wdt+hvz]).
tagword(nr+md,[nr+md]).
tagword(nn+in,[nn+in]).
tagword(nn+hvd,[nn+hvd]).
tagword(wdt+dod,[wdt+dod]).
tagword(fw-ber,[fw-ber]).
tagword(fw-nn-s,[fw-nn-s]).
tagword(wrb+do,[wrb+do]).
tagword(wrb+in,[wrb+in]).
tagword(hv+to,[hv+to]).
tagword(pn+md,[pn+md]).
tagword(wps+hvz,[wps+hvz]).
tagword(wrb+md,[wrb+md]).
tagword(fw-ppl,[fw-ppl]).
tagword(dt-s,[dt-s]).
tagword(fw-nr,[fw-nr]).
tagword(fw-at+nn,[fw-at+nn]).
tagword(pn+hvz,[pn+hvz]).
tagword(ex+hvz,[ex+hvz]).
tagword(wrb+ber,[wrb+ber]).
tagword(ppss+bez,[ppss+bez]).
tagword(bem-negation,[bem-negation]).
tagword(nn+md,[nn+md]).
tagword(ppss+bez-negation,[ppss+bez-negation]).
tagword(rbr+cs,[rbr+cs]).
tagword(in+ppo,[in+ppo]).
tagword(to+vb,[to+vb]).
tagword(in+in,[in+in]).
tagword(do+ppss,[do+ppss]).
tagword(wrb+doz,[wrb+doz]).
tagword(ex+hvd,[ex+hvd]).
tagword(wdt+do+pps,[wdt+do+pps]).
tagword(nr-s,[nr-s]).
tagword(wrb+dod,[wrb+dod]).
tagword(vb+to,[vb+to]).
tagword(wrb+dod-negation,[wrb+dod-negation]).
tagword(vb+rp,[vb+rp]).
tagword(wdt+ber,[wdt+ber]).
tagword(ppss+vb,[ppss+vb]).
tagword(vb+at,[vb+at]).
tagword(nns+md,[nns+md]).
tagword(dts+bez,[dts+bez]).
tagword(rb+cs,[rb+cs]).
tagword(ap-s,[ap-s]).
tagword(nrs,[nrs]).
tagword(fw-od,[fw-od]).
tagword(vbn+to,[vbn+to]).
tagword(fw-ppss,[fw-ppss]).
tagword(fw-wdt,[fw-wdt]).
tagword(md+hv,[md+hv]).
tagword(np+md,[np+md]).
tagword(pn+bez,[pn+bez]).
tagword(np+hvz,[np+hvz]).
tagword(wps+hvd,[wps+hvd]).
tagword(rp+in,[rp+in]).
tagword(rn,[rn]).
tagword(fw-in+np,[fw-in+np]).
tagword(fw-cc,[fw-cc]).
tagword(fw-ppss+hv,[fw-ppss+hv]).
tagword(wql,[wql]).
tagword(fw-ppo,[fw-ppo]).
tagword(fw-vbz,[fw-vbz]).
tagword(fw-cs,[fw-cs]).
tagword(pn+hvd,[pn+hvd]).
tagword(wrb+bez,[wrb+bez]).
tagword(hv-negation,[hv-negation]).
tagword(vbg+to,[vbg+to]).
tagword(ppss+hvd,[ppss+hvd]).
tagword(pps+hvd,[pps+hvd]).
tagword(dt+md,[dt+md]).
tagword(nps-s,[nps-s]).
tagword(bed-negation,[bed-negation]).
tagword(ber-negation,[ber-negation]).
tagword(rb+bez,[rb+bez]).
tagword(fw-negation,[fw-negation]).
tagword(pn-s,[pn-s]).
tagword(wps+md,[wps+md]).
tagword(abl,[abl]).
tagword(hvd-negation,[hvd-negation]).
tagword(pps+md,[pps+md]).
tagword(nn+hvz,[nn+hvz]).
tagword(nn+bez,[nn+bez]).
tagword(md+to,[md+to]).
tagword(ex+md,[ex+md]).
tagword(dtx,[dtx]).
tagword(wps+bez,[wps+bez]).
tagword(wdt+bez,[wdt+bez]).
tagword(hvz-negation,[hvz-negation]).
tagword(doz-negation,[doz-negation]).
tagword(fw-vbg,[fw-vbg]).
tagword(fw-bez,[fw-bez]).
tagword(fw-np,[fw-np]).
tagword(rbt,[rbt]).
tagword(jjs,[jjs]).
tagword(dt+bez,[dt+bez]).
tagword(dod-negation,[dod-negation]).
tagword(bedz-negation,[bedz-negation]).
tagword(np+bez,[np+bez]).
tagword(rb-s,[rb-s]).
tagword(fw-at,[fw-at]).
tagword(fw-in+at,[fw-in+at]).
tagword(fw-vb,[fw-vb]).
tagword(abx,[abx]).
tagword(hvn,[hvn]).
tagword(doz,[doz]).
tagword(fw-vbn,[fw-vbn]).
tagword(beg,[beg]).
tagword(quote,[quote]).
tagword(hvz,[hvz]).
tagword(colon,[colon]).
tagword(fw-in+nn,[fw-in+nn]).
tagword(jjt,[jjt]).
tagword(fw-jj,[fw-jj]).
tagword(nr,[nr]).
tagword(nps,[nps]).
tagword(hvg,[hvg]).
tagword(ppss+bem,[ppss+bem]).
tagword(dts,[dts]).
tagword(dod,[dod]).
tagword(vb+ppo,[vb+ppo]).
tagword(bem,[bem]).
tagword(start_paran,[start_paran]).
tagword(end_paran,[end_paran]).
tagword(ber,[ber]).
tagword(hv,[hv]).
tagword(do-negation,[do-negation]).
tagword(od,[od]).
tagword(ex,[ex]).
tagword(ppls,[ppls]).
tagword(rbr,[rbr]).
tagword(nns-ss,[nns-ss]).
tagword(fw-uh,[fw-uh]).
tagword(fw-pp-s,[fw-pp-s]).
tagword(uh,[uh]).
tagword(pps+hvz,[pps+hvz]).
tagword(ben,[ben]).
tagword(hvd,[hvd]).
tagword(np-s,[np-s]).
tagword(wpo,[wpo]).
tagword(bed,[bed]).
tagword(negation,[negation]).
tagword(ppl,[ppl]).
tagword(cd,[cd]).
tagword(fw-nns,[fw-nns]).
tagword(abn,[abn]).
tagword(ex+bez,[ex+bez]).
tagword(dti,[dti]).
tagword(endquote,[endquote]).
tagword(wrb,[wrb]).
tagword(vbz,[vbz]).
tagword(ppss+md,[ppss+md]).
tagword(dt,[dt]).
tagword(bez-negation,[bez-negation]).
tagword(fw-rb,[fw-rb]).
tagword(fw-in,[fw-in]).
tagword(fw-nn,[fw-nn]).
tagword(ppss+hv,[ppss+hv]).
tagword(md-negation,[md-negation]).
tagword(be,[be]).
tagword(qlp,[qlp]).
tagword(bez,[bez]).
tagword(ppss+ber,[ppss+ber]).
tagword(pps+bez,[pps+bez]).
tagword(pn,[pn]).
tagword(md,[md]).
tagword(vb,[vb]).
tagword(ppo,[ppo]).
tagword(to,[to]).
tagword(do,[do]).
tagword(rb,[rb]).
tagword(pp-ss,[pp-ss]).
tagword(vbn,[vbn]).
tagword(rp,[rp]).
tagword(pps,[pps]).
tagword(hyphen,[hyphen]).
tagword(nns,[nns]).
tagword(wps,[wps]).
tagword(vbd,[vbd]).
tagword(np,[np]).
tagword(pp-s,[pp-s]).
tagword(cc,[cc]).
tagword(wp-s,[wp-s]).
tagword(ap,[ap]).
tagword(nn-s,[nn-s]).
tagword(cs,[cs]).
tagword(jjr,[jjr]).
tagword(ql,[ql]).
tagword(wdt,[wdt]).
tagword(ppss,[ppss]).
tagword(comma,[comma]).
tagword(in,[in]).
tagword(at,[at]).
tagword(jj,[jj]).
tagword(nn,[nn]).
tagword(bedz,[bedz]).
tagword(vbg,[vbg]).
tagword(dot,[dot]).
