:- cl('../../config.pl').
:- require('corpora/brown/parts/brown_part1.pl').
:- require('corpora/brown/parts/brown_part2.pl').
:- require('corpora/brown/parts/brown_part3.pl').
:- require('corpora/brown/parts/brown_part4.pl').
:- require('corpora/brown/parts/brown_part5.pl').
:- require('corpora/brown/parts/brown_part6.pl').
:- require('corpora/brown/parts/brown_part7.pl').
:- require('corpora/brown/parts/brown_part8.pl').
:- require('corpora/brown/parts/brown_part9.pl').
:- require('corpora/brown/parts/brown_part10.pl').
:- require('corpora/brown/parts/brown_part11.pl').
:- require('corpora/brown/parts/brown_part12.pl').
:- require('corpora/brown/parts/brown_part13.pl').
:- require('corpora/brown/parts/brown_part14.pl').
:- require('corpora/brown/parts/brown_part15.pl').
:- require('corpora/brown/parts/brown_part16.pl').
:- require('corpora/brown/parts/brown_part17.pl').
:- require('corpora/brown/parts/brown_part18.pl').
:- require('corpora/brown/parts/brown_part19.pl').
:- require('corpora/brown/parts/brown_part20.pl').
:- require('corpora/brown/parts/brown_part21.pl').
:- require('corpora/brown/parts/brown_part22.pl').
:- require('corpora/brown/parts/brown_part23.pl').
:- require('corpora/brown/parts/brown_part24.pl').
:- require('corpora/brown/parts/brown_part25.pl').
:- require('corpora/brown/parts/brown_part26.pl').
:- require('corpora/brown/parts/brown_part27.pl').
:- require('corpora/brown/parts/brown_part28.pl').
:- require('corpora/brown/parts/brown_part29.pl').
:- require('corpora/brown/parts/brown_part30.pl').
:- require('corpora/brown/parts/brown_part31.pl').
:- require('corpora/brown/parts/brown_part32.pl').
:- require('corpora/brown/parts/brown_part33.pl').
:- require('corpora/brown/parts/brown_part34.pl').
:- require('corpora/brown/parts/brown_part35.pl').
:- require('corpora/brown/parts/brown_part36.pl').
:- require('corpora/brown/parts/brown_part37.pl').
:- require('corpora/brown/parts/brown_part38.pl').
:- require('corpora/brown/parts/brown_part39.pl').
:- require('corpora/brown/parts/brown_part40.pl').
:- require('corpora/brown/parts/brown_part41.pl').
:- require('corpora/brown/parts/brown_part42.pl').
:- require('corpora/brown/parts/brown_part43.pl').
:- require('corpora/brown/parts/brown_part44.pl').
:- require('corpora/brown/parts/brown_part45.pl').
:- require('corpora/brown/parts/brown_part46.pl').
:- require('corpora/brown/parts/brown_part47.pl').
:- require('corpora/brown/parts/brown_part48.pl').
:- require('corpora/brown/parts/brown_part49.pl').
:- require('corpora/brown/parts/brown_part50.pl').
:- require('corpora/brown/parts/brown_part51.pl').
:- require('corpora/brown/parts/brown_part52.pl').
:- require('corpora/brown/parts/brown_part53.pl').
:- require('corpora/brown/parts/brown_part54.pl').
:- require('corpora/brown/parts/brown_part55.pl').
:- require('corpora/brown/parts/brown_part56.pl').
:- require('corpora/brown/parts/brown_part57.pl').
:- require('corpora/brown/parts/brown_part58.pl').
:- require('corpora/brown/parts/brown_part59.pl').
:- require('corpora/brown/parts/brown_part60.pl').
:- require('corpora/brown/parts/brown_part61.pl').
:- require('corpora/brown/parts/brown_part62.pl').
:- require('corpora/brown/parts/brown_part63.pl').
:- require('corpora/brown/parts/brown_part64.pl').
:- require('corpora/brown/parts/brown_part65.pl').
:- require('corpora/brown/parts/brown_part66.pl').
:- require('corpora/brown/parts/brown_part67.pl').
:- require('corpora/brown/parts/brown_part68.pl').
:- require('corpora/brown/parts/brown_part69.pl').
:- require('corpora/brown/parts/brown_part70.pl').
:- require('corpora/brown/parts/brown_part71.pl').
:- require('corpora/brown/parts/brown_part72.pl').
:- require('corpora/brown/parts/brown_part73.pl').
:- require('corpora/brown/parts/brown_part74.pl').
:- require('corpora/brown/parts/brown_part75.pl').
:- require('corpora/brown/parts/brown_part76.pl').
:- require('corpora/brown/parts/brown_part77.pl').
:- require('corpora/brown/parts/brown_part78.pl').
:- require('corpora/brown/parts/brown_part79.pl').
:- require('corpora/brown/parts/brown_part80.pl').
:- require('corpora/brown/parts/brown_part81.pl').
:- require('corpora/brown/parts/brown_part82.pl').
:- require('corpora/brown/parts/brown_part83.pl').
:- require('corpora/brown/parts/brown_part84.pl').
:- require('corpora/brown/parts/brown_part85.pl').
:- require('corpora/brown/parts/brown_part86.pl').
:- require('corpora/brown/parts/brown_part87.pl').