tagmap('dt$',dt-s).
tagmap('fw-cs',fw-cs).
tagmap('fw-od',fw-od).
tagmap('nn+bez',nn+bez).
tagmap('fw-bez', fw-bez).
tagmap('vb+vb', vb+vb).
tagmap('pps+md', pps+md).
tagmap('fw-in+at',fw-in+at).
tagmap('fw-rb',fw-rb).
tagmap('beg',beg).
tagmap('dod*',dod-negation).
tagmap('fw-at+nn',fw-at+nn).
tagmap('fw-in',fw-in).
tagmap('wrb+doz',wrb+doz).
tagmap('dti',dti).
tagmap('dt+md',dt+md).
tagmap('fw-at+np',fw-at+np).
tagmap('nps',nps).
tagmap('nn+nn',nn+nn).
tagmap('ppss+vb',ppss+vb).
tagmap('wdt',wdt).
tagmap('wp$',wp-s).
tagmap('fw-be',fw-be).
tagmap('vbd',vbd).
tagmap('hr',hr).
tagmap('wdt+ber+pp',wdt+ber+pp).
tagmap('pp$$',pp-ss).
tagmap('bem',bem).
tagmap('doz*',doz-negation).
tagmap('wps+bez',wps+bez).
tagmap('pn+bez',pn+bez).
tagmap('ex',ex).
tagmap('nns$',nns-ss).
tagmap('ben',ben).
tagmap('fw-vbz',fw-vbz).
tagmap('vbg',vbg).
tagmap('hvz',hvz).
tagmap('wrb+do',wrb+do).
tagmap('wrb+md',wrb+md).
tagmap('nil',nil).
tagmap('hv',hv).
tagmap('np+hvz',np+hvz).
tagmap('nn',nn).
tagmap('hv+to',hv+to).
tagmap('fw-nn$',fw-nn-s).
tagmap('ap$',ap-s).
tagmap('ql',ql).
tagmap('fw-uh',fw-uh).
tagmap('np',np).
tagmap('ber',ber).
tagmap('fw-jjr',fw-jjr).
tagmap('pps+hvz',pps+hvz).
tagmap('pn$',pn-s).
tagmap('in+in',in+in).
tagmap('fw-in+at-t',fw-in+at-t).
tagmap('ex+hvd',ex+hvd).
tagmap('wpo',wpo).
tagmap('nr',nr).
tagmap('nr$',nr-s).
tagmap('fw-jjt',fw-jjt).
tagmap('dts',dts).
tagmap('in+ppo',in+ppo).
tagmap('wdt+hvz',wdt+hvz).
tagmap('nn+md',nn+md).
tagmap('vbn',vbn).
tagmap('fw-pp$',fw-pp-s).
tagmap('ap',ap).
tagmap('vb+in',vb+in).
tagmap('wps',wps).
tagmap('to',to).
tagmap('jj$',jj-s).
tagmap('dtx',dtx).
tagmap('bedz*',bedz-negation).
tagmap('md',md).
tagmap('bez',bez).
tagmap('do',do).
tagmap('bed*',bed-negation).
tagmap('at',at).
tagmap('do+ppss',do+ppss).
tagmap('fw-to+vb',fw-to+vb).
tagmap('np+bez',np+bez).
tagmap('dt+bez',dt+bez).
tagmap(startquote,endquote).
tagmap('md*',md-negation).
tagmap('qlp',qlp).
tagmap('ap+ap',ap+ap).
tagmap(endquote,endquote).
tagmap('wrb+ber',wrb+ber).
tagmap('jj',jj).
tagmap('fw-ppl',fw-ppl).
tagmap('pps+bez',pps+bez).
tagmap('fw-dt+bez',fw-dt+bez).
tagmap('ppss+ber-n',ppss+ber-n).
tagmap('md+ppss',md+ppss).
tagmap('dt',dt).
tagmap('fw-nns',fw-nns).
tagmap('md+hv',md+hv).
tagmap('pn+md',pn+md).
tagmap('fw-ppo+in',fw-ppo+in).
tagmap('wrb',wrb).
tagmap('fw-ppss',fw-ppss).
tagmap('fw-ppo',fw-ppo).
tagmap('bez*',bez-negation).
tagmap('nrs',nrs).
tagmap('vbz',vbz).
tagmap('ppss+hvd',ppss+hvd).
tagmap('fw-ppl+vbz',fw-ppl+vbz).
tagmap('cc',cc).
tagmap('cd',cd).
tagmap('fw-nn',fw-nn).
tagmap('vb',vb).
tagmap('nn+hvd',nn+hvd).
tagmap('fw-pps',fw-pps).
tagmap('wrb+bez',wrb+bez).
tagmap('fw-hv',fw-hv).
tagmap('vb+rp',vb+rp).
tagmap('nn$',nn-s).
tagmap('jjr',jjr).
tagmap('fw-np',fw-np).
tagmap('fw-ql',fw-ql).
tagmap('bem*',bem-negation).
tagmap('jjs',jjs).
tagmap('wrb+dod*',wrb+dod-negation).
tagmap('ppss',ppss).
tagmap('fw-rb+cc',fw-rb+cc).
tagmap('jjt',jjt).
tagmap('md+to',md+to).
tagmap('pn',pn).
tagmap('dts+bez',dts+bez).
tagmap('fw-nr',fw-nr).
tagmap('1,000',discard).
tagmap('ex+md',ex+md).
tagmap('dod',dod).
tagmap('acre',acre).
tagmap('nns+md',nns+md).
tagmap('bedz',bedz).
tagmap('pp$',pp-s).
tagmap('ex+hvz',ex+hvz).
tagmap('wrb+in',wrb+in).
tagmap('--',hyphen).
tagmap('rbr+cs',rbr+cs).
tagmap('rp+in',rp+in).
tagmap('\'',discard).
tagmap('_quote_',quote).
tagmap('pn+hvd',pn+hvd).
tagmap('to+vb',to+vb).
tagmap('hvd*',hvd-negation).
tagmap('wps+hvd',wps+hvd).
tagmap('*0F.',discard).
tagmap('fw-*',fw-negation).
tagmap('(',start_paran).
tagmap(')',end_paran).
tagmap('wdt+do+pps',wdt+do+pps).
tagmap('fw-at',fw-at).
tagmap('nn+in',nn+in).
tagmap('*',negation).
tagmap('vbg+to',vbg+to).
tagmap('fw-jj',fw-jj).
tagmap('wdt+dod',wdt+dod).
tagmap('do*',do-negation).
tagmap('ppl',ppl).
tagmap('cd$',cd-s).
tagmap(',',comma).
tagmap('rb$',rb-s).
tagmap('np+md',np+md).
tagmap('cs',cs).
tagmap('abl',abl).
tagmap('od',od).
tagmap('nns',nns).
tagmap('jj+jj',jj+jj).
tagmap('fw-dt',fw-dt).
tagmap('hvz*',hvz-negation).
tagmap('.',dot).
tagmap('ppo',ppo).
tagmap('abn',abn).
tagmap('rb',rb).
tagmap('wrb+dod',wrb+dod).
tagmap('ppls',ppls).
tagmap('rb+cs',rb+cs).
tagmap('in',in).
tagmap('rb+bez',rb+bez).
tagmap('ex+bez',ex+bez).
tagmap('ppss+bem',ppss+bem).
tagmap('fw-cc',fw-cc).
tagmap('fw-nps',fw-nps).
tagmap('jjr+cs',jjr+cs).
tagmap('fw-cd',fw-cd).
tagmap('fw-vb',fw-vb).
tagmap('ppss+hv',ppss+hv).
tagmap('fw-wdt',fw-wdt).
tagmap('pps',pps).
tagmap('wdt+ber',wdt+ber).
tagmap('ppss+bez*',ppss+bez-negation).
tagmap('fw-vbd',fw-vbd).
tagmap('hvd',hvd).
tagmap('nr+md',nr+md).
tagmap('be',be).
tagmap('nn+hvz',nn+hvz).
tagmap('fw-pn',fw-pn).
tagmap('wps+md',wps+md).
tagmap('vb+to',vb+to).
tagmap('fw-vbg',fw-vbg).
tagmap('hvg',hvg).
tagmap('ppss+ber',ppss+ber).
tagmap('np$',np-s).
tagmap('nps$',nps-s).
tagmap('pps+hvd',pps+hvd).
tagmap('uh',uh).
tagmap('fw-in+nn',fw-in+nn).
tagmap('abx',abx).
tagmap('wql',wql).
tagmap('vb+at',vb+at).
tagmap(':',colon).
tagmap('rbr',rbr).
tagmap('fw-in+np',fw-in+np).
tagmap('hv*',hv-negation).
tagmap('doz',doz).
tagmap('fw-ber',fw-ber).
tagmap('vb+jj',vb+jj).
tagmap('rn',rn).
tagmap('vbn+to',vbn+to).
tagmap('wdt+bez',wdt+bez).
tagmap('vb+ppo',vb+ppo).
tagmap('rbt',rbt).
tagmap('fw-dts',fw-dts).
tagmap('ber*',ber-negation).
tagmap('fw-wpo',fw-wpo).
tagmap('rp',rp).
tagmap('ppss+md',ppss+md).
tagmap('pn+hvz',pn+hvz).
tagmap('wps+hvz',wps+hvz).
tagmap('hvn',hvn).
tagmap('ppss+bez',ppss+bez).
tagmap('fw-vbn',fw-vbn).
tagmap('fw-ppss+hv',fw-ppss+hv).
tagmap('fw-wps',fw-wps).
tagmap('bed',bed).
